repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.6.2
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.10b0]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
